name: Laporkan Bug
description: Laporkan bug mengenai situs.
title: '[BUG] example.com'
labels: 
  - bug
  - sites
assignees: 
  - ryukora
body:
  - type: markdown
    attributes:
      value: |
        Terima kasih telah melaporkan adanya masalah!
        
        Pastikan website yang akan dilaporkan tidak terdapat duplikat issue.
  - type: input
    id: domainataulain
    attributes:
      label: Domain atau lain
      description: Masukkan domain atau lain
      placeholder: example.com, ...
    validations:
      required: true
  - type: input
    id: deskripsi
    attributes:
      label: Alasan / Deskripsi mengenai bug
      description: Deskripsi jelas dan ringkas tentang apa yang terjadi.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Jika ada, tambahkan screenshot untuk membantu menjelaskan mengenai bug.
  - type: input
    id: isp
    attributes:
      label: ISP Apa yang anda gunakan
      placeholder: Telkom, IndiHome, dll.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Sistem Operasi (OS)
      description: Masukkan sistem operasi yang Anda gunakan.
      placeholder: Windows 11, macOS, Debian Linux
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Masukkan browser yang Anda gunakan.
      placeholder: Chrome, Firefox, Edge
    validations:
      required: true
  - type: textarea
    id: optional-comment
    attributes:
      label: Komentar
